### ISSUE TITLE
Multi-hop health-checking

### ISSUE THREAD

**Issue by film42** [film42/pgreplbot#18]
We didn't enable multi-hop health-checking to reduce the connection amplification caused by many concurrent health-checks. However, since we added the 1-second health-check cache in #13 , I wonder if we should enabled a max-hop setting and recursively hop from postgres server to postgres server until we've found the primary.

Thoughts @benschinn ?

**Comment by benschinn** [comment]
Sounds good. @film42 should we set the max-hop setting in the config?

**Comment by film42** [comment]
I think so! We can also start with hard-coding to 3 hops to support the MX use-case first and add configuration later if it makes more sense. Up to you!
