### ISSUE TITLE
Replica byte lag health check

### ISSUE THREAD

**Issue by film42** [film42/pgreplbot#3]
### Description

A replica should be health checked by looking at the byte lag relative to the current primary.

### Details

Scenario we must support:
1. In the chain `Replica1 -> Primary`, it should connect to the `Primary` node to compare the `pg_current_wal_lsn()`.

Considerations but not required:

1. In the chain `Replica2 -> Replica1 -> Primary`, the `Replica2` database should connect to `Replica1` and then to `Primary` to measure the true byte lag. If `Replica1` had stopped replicating from `Primary`, `Replica2` might see it's up-to-date with `Replica1` and a health replica. This would be bad. That's why we need to compare with the primary DB.

### UX 

We can hard code the byte lag for now, and make it configurable in the future. For future sketching, we could try using a config file, env variable, or even an http query param, ex `GET /replica?max_allowable_byte_lag=12344`.

**Comment by benschinn** [comment]
Working on this!
